[Tue Jan 21 16:25:35.465908 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49707] mod_wsgi (pid=7788): Failed to exec Python script file 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'., referer: http://localhost/
[Tue Jan 21 16:25:35.466911 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49707] mod_wsgi (pid=7788): Exception occurred processing WSGI script 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'., referer: http://localhost/
[Tue Jan 21 16:25:35.472927 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49707] Traceback (most recent call last):\r, referer: http://localhost/
[Tue Jan 21 16:25:35.472927 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49707]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi", line 5, in <module>\r, referer: http://localhost/
[Tue Jan 21 16:25:35.472927 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49707]     from app import app as application\r, referer: http://localhost/
[Tue Jan 21 16:25:35.472927 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49707] ModuleNotFoundError: No module named 'app'\r, referer: http://localhost/
[Tue Jan 21 16:25:40.517887 2020] [wsgi:error] [pid 7788:tid 1116] [client ::1:49708] mod_wsgi (pid=7788): Failed to exec Python script file 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'.
[Tue Jan 21 16:25:40.517887 2020] [wsgi:error] [pid 7788:tid 1116] [client ::1:49708] mod_wsgi (pid=7788): Exception occurred processing WSGI script 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'.
[Tue Jan 21 16:25:40.517887 2020] [wsgi:error] [pid 7788:tid 1116] [client ::1:49708] Traceback (most recent call last):\r
[Tue Jan 21 16:25:40.517887 2020] [wsgi:error] [pid 7788:tid 1116] [client ::1:49708]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi", line 5, in <module>\r
[Tue Jan 21 16:25:40.517887 2020] [wsgi:error] [pid 7788:tid 1116] [client ::1:49708]     from app import app as application\r
[Tue Jan 21 16:25:40.517887 2020] [wsgi:error] [pid 7788:tid 1116] [client ::1:49708] ModuleNotFoundError: No module named 'app'\r
[Tue Jan 21 16:25:40.562003 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49709] mod_wsgi (pid=7788): Failed to exec Python script file 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'., referer: http://localhost/
[Tue Jan 21 16:25:40.562003 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49709] mod_wsgi (pid=7788): Exception occurred processing WSGI script 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'., referer: http://localhost/
[Tue Jan 21 16:25:40.562003 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49709] Traceback (most recent call last):\r, referer: http://localhost/
[Tue Jan 21 16:25:40.562003 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49709]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi", line 5, in <module>\r, referer: http://localhost/
[Tue Jan 21 16:25:40.562003 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49709]     from app import app as application\r, referer: http://localhost/
[Tue Jan 21 16:25:40.562003 2020] [wsgi:error] [pid 7788:tid 1120] [client ::1:49709] ModuleNotFoundError: No module named 'app'\r, referer: http://localhost/
[Tue Jan 21 16:27:20.508615 2020] [wsgi:error] [pid 6528:tid 1128] [client ::1:49732] found user\r, referer: http://localhost/login
[Tue Jan 21 16:27:29.102041 2020] [wsgi:error] [pid 6528:tid 1128] [client ::1:49732] Loading pages (1/6)\r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:29.102041 2020] [wsgi:error] [pid 6528:tid 1128] [client ::1:49732] [>                                                           ] 0%\r[======>                                                     ] 10%\r[==========================>                                 ] 44%\rWarning: Failed to load http://localhost/static/img/Gaurav V Gulve BE IT A/mcoe_logo.png (ignore)\r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:29.102041 2020] [wsgi:error] [pid 6528:tid 1128] [client ::1:49732] [=====================================>                      ] 62%\r[=======================================>                    ] 65%\r[========================================>                   ] 68%\r[==========================================>                 ] 70%\r[===========================================>                ] 73%\r[=============================================>              ] 76%\r[===============================================>            ] 79%\r[================================================>           ] 81%\r[=================================================>          ] 83%\r[===================================================>        ] 86%\r[============================================================] 100%\rCounting pages (2/6)                                               \r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:29.102041 2020] [wsgi:error] [pid 6528:tid 1128] [client ::1:49732] [============================================================] Object 1 of 1\rResolving links (4/6)                                                       \r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:29.102041 2020] [wsgi:error] [pid 6528:tid 1128] [client ::1:49732] [============================================================] Object 1 of 1\rLoading headers and footers (5/6)                                           \r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:29.102041 2020] [wsgi:error] [pid 6528:tid 1128] [client ::1:49732] Printing pages (6/6)\r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:29.102041 2020] [wsgi:error] [pid 6528:tid 1128] [client ::1:49732] [>                                                           ] Preparing\r[===================>                                        ] Page 1 of 3\r[=======================================>                    ] Page 2 of 3\r[============================================================] Page 3 of 3\rDone                                                                      \r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:42.365072 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49744] Loading pages (1/6)\r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:42.365072 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49744] [>                                                           ] 0%\r[======>                                                     ] 10%\r[==========================>                                 ] 44%\rWarning: Failed to load http://localhost/static/img/Gaurav V Gulve BE IT A/mcoe_logo.png (ignore)\r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:42.365072 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49744] [=====================================>                      ] 62%\r[======================================>                     ] 64%\r[========================================>                   ] 67%\r[=========================================>                  ] 69%\r[==========================================>                 ] 71%\r[============================================>               ] 74%\r[=============================================>              ] 76%\r[===============================================>            ] 79%\r[================================================>           ] 81%\r[=================================================>          ] 83%\r[===================================================>        ] 86%\r[============================================================] 100%\rCounting pages (2/6)                                               \r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:42.365072 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49744] [============================================================] Object 1 of 1\rResolving links (4/6)                                                       \r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:42.365072 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49744] [============================================================] Object 1 of 1\rLoading headers and footers (5/6)                                           \r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:42.365072 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49744] Printing pages (6/6)\r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:27:42.365072 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49744] [>                                                           ] Preparing\r[===================>                                        ] Page 1 of 3\r[=======================================>                    ] Page 2 of 3\r[============================================================] Page 3 of 3\rDone                                                                      \r\r, referer: http://localhost/view_profile/gauravgulveoff%40gmail.com
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762] [2020-01-21 16:28:39,998] ERROR in app: Exception on /send_mail [POST]\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762] Traceback (most recent call last):\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     response = self.full_dispatch_request()\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     rv = self.handle_user_exception(e)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     reraise(exc_type, exc_value, tb)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     raise value\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     rv = self.dispatch_request()\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 51, in wrap\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     return f(*args, **kwargs)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 84, in wrap\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     return f(*args, **kwargs)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 692, in send_mail\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     mail.send(msg)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask_mail.py", line 491, in send\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     with self.connect() as connection:\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask_mail.py", line 144, in __enter__\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     self.host = self.configure_host()\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask_mail.py", line 156, in configure_host\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\Lib\\smtplib.py", line 1034, in __init__\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     SMTP.__init__(self, host, port, local_hostname, timeout,\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\Lib\\smtplib.py", line 253, in __init__\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     (code, msg) = self.connect(host, port)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\Lib\\smtplib.py", line 339, in connect\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     self.sock = self._get_socket(host, port, self.timeout)\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\Lib\\smtplib.py", line 1040, in _get_socket\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     new_socket = socket.create_connection((host, port), timeout,\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\Lib\\socket.py", line 787, in create_connection\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     for res in getaddrinfo(host, port, 0, SOCK_STREAM):\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]   File "c:\\users\\admin\\appdata\\local\\programs\\python\\python38\\Lib\\socket.py", line 918, in getaddrinfo\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762]     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\r, referer: http://localhost/send_mail
[Tue Jan 21 16:28:40.004852 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:49762] socket.gaierror: [Errno 11001] getaddrinfo failed\r, referer: http://localhost/send_mail
[Tue Jan 28 14:29:04.264723 2020] [wsgi:error] [pid 6528:tid 1124] [client ::1:51350] found user\r, referer: http://localhost/login
[Tue Jan 28 14:34:41.913866 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:51392] found user\r, referer: http://localhost/login
[Tue Jan 28 14:37:03.509400 2020] [wsgi:error] [pid 6528:tid 1116] [client ::1:51420] 0\r, referer: http://localhost/dashboard
[Tue Jan 28 14:37:10.961126 2020] [wsgi:error] [pid 6528:tid 1148] [client ::1:51428] 0\r, referer: http://localhost/dashboard
[Tue Jan 28 14:38:24.756008 2020] [wsgi:error] [pid 6528:tid 1116] [client ::1:51451] found user\r, referer: http://localhost/login
[Wed Jan 29 12:08:49.273071 2020] [wsgi:error] [pid 1824:tid 1084] [client 172.16.19.67:59556] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:14:41.405413 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44534] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:23:09.165705 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.18.232:48190] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:26:37.502417 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.18.232:48218] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:26:58.798039 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.18.232:48222] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:28:56.764042 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.18.232:48258] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:30:26.124810 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.18.232:48286] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682] [2020-01-29 12:30:27,818] ERROR in app: Exception on /view_chart/gauravgulveoff@gmail.com [GET]\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682] Traceback (most recent call last):\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]     response = self.full_dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]     rv = self.handle_user_exception(e)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]     reraise(exc_type, exc_value, tb)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]     raise value\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]     rv = self.dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 871, in view_chart\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682]     for achievement in user1['achievements']:\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:27.896526 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44682] KeyError: 'achievements'\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684] [2020-01-29 12:30:32,526] ERROR in app: Exception on /view_chart/sameer.s.ambekar@gmail.com [GET]\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684] Traceback (most recent call last):\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]     response = self.full_dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]     rv = self.handle_user_exception(e)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]     reraise(exc_type, exc_value, tb)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]     raise value\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]     rv = self.dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 871, in view_chart\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684]     for achievement in user1['achievements']:\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:32.527843 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44684] KeyError: 'achievements'\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690] [2020-01-29 12:30:55,521] ERROR in app: Exception on /view_chart/sameer.s.ambekar@gmail.com [GET]\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690] Traceback (most recent call last):\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]     response = self.full_dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]     rv = self.handle_user_exception(e)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]     reraise(exc_type, exc_value, tb)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]     raise value\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]     rv = self.dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 871, in view_chart\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690]     for achievement in user1['achievements']:\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:30:55.522011 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44690] KeyError: 'achievements'\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694] [2020-01-29 12:31:16,780] ERROR in app: Exception on /view_chart/gauravgulveoff@gmail.com [GET]\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694] Traceback (most recent call last):\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]     response = self.full_dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]     rv = self.handle_user_exception(e)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]     reraise(exc_type, exc_value, tb)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]     raise value\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]     rv = self.dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 871, in view_chart\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694]     for achievement in user1['achievements']:\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:16.780562 2020] [wsgi:error] [pid 1824:tid 1096] [client 172.16.19.71:44694] KeyError: 'achievements'\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696] [2020-01-29 12:31:25,042] ERROR in app: Exception on /view_chart/sameer.s.ambekar@gmail.com [GET]\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696] Traceback (most recent call last):\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 2446, in wsgi_app\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]     response = self.full_dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1951, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]     rv = self.handle_user_exception(e)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1820, in handle_user_exception\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]     reraise(exc_type, exc_value, tb)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]     raise value\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1949, in full_dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]     rv = self.dispatch_request()\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\app.py", line 1935, in dispatch_request\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]     return self.view_functions[rule.endpoint](**req.view_args)\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 871, in view_chart\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696]     for achievement in user1['achievements']:\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:31:25.043542 2020] [wsgi:error] [pid 1824:tid 940] [client 172.16.19.71:44696] KeyError: 'achievements'\r, referer: http://172.16.2.61/dashboard
[Wed Jan 29 12:35:01.490572 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44768] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:38:15.772400 2020] [wsgi:error] [pid 1824:tid 1104] [client 172.16.18.232:48346] 2020-09-01 00:00:00\r, referer: http://172.16.2.61/profile
[Wed Jan 29 12:41:40.045207 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.68:33488] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:44:25.537974 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44818] 2020-09-01 00:00:00\r, referer: http://172.16.2.61/send_mail
[Wed Jan 29 12:45:07.395321 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44842] done\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228?email=gauravgulveoff%40gmail.com
[Wed Jan 29 12:45:07.403342 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44842] <p>Very Good..</p>\r\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228?email=gauravgulveoff%40gmail.com
[Wed Jan 29 12:45:07.403342 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44842] \r\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228?email=gauravgulveoff%40gmail.com
[Wed Jan 29 12:45:07.403342 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44842] <p>Regular Student</p>\r\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228?email=gauravgulveoff%40gmail.com
[Wed Jan 29 12:45:07.403342 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44842] \r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228?email=gauravgulveoff%40gmail.com
[Wed Jan 29 12:45:07.404345 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44842] {'mentor_email': 'swapna.s.bhavsar@gmail.com', 'meeting_id': 'Regarding Placement Details6228', 'subject': 'Regarding Placement Details', 'time': '1.30', 'venue': 'SL I', 'date': '2020-09-01', 'batch': 'BE IT A batch A', 'done': 'yes', 'remark': '<p>Very Good..</p>\\r\\n\\r\\n<p>Regular Student</p>\\r\\n', 'last_updated_on': datetime.datetime(2020, 1, 29, 12, 45, 7, 393000)}\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228?email=gauravgulveoff%40gmail.com
[Wed Jan 29 12:45:18.890901 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44844] 2020-09-01 00:00:00\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228?email=gauravgulveoff%40gmail.com
[Wed Jan 29 12:45:40.310881 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44864] <p>Very Good..</p>\r\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228
[Wed Jan 29 12:45:40.310881 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44864] \r\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228
[Wed Jan 29 12:45:40.310881 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44864] <p>Regular Student</p>\r\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228
[Wed Jan 29 12:45:40.310881 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44864] \r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228
[Wed Jan 29 12:45:40.310881 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.19.71:44864] {'mentor_email': 'swapna.s.bhavsar@gmail.com', 'meeting_id': 'Regarding Placement Details6228', 'subject': 'Regarding Placement Details', 'time': '1.30', 'venue': 'SL I', 'date': '2020-09-01', 'batch': 'BE IT A batch A', 'done': 'yes', 'remark': '<p>Very Good..</p>\\r\\n\\r\\n<p>Regular Student</p>\\r\\n', 'last_updated_on': datetime.datetime(2020, 1, 29, 12, 45, 7, 393000)}\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228
[Wed Jan 29 12:46:08.767580 2020] [wsgi:error] [pid 1824:tid 1116] [client 172.16.19.71:44866] 2020-09-01 00:00:00\r, referer: http://172.16.2.61/meeting/Regarding%20Placement%20Details6228?email=gauravgulveoff%40gmail.com
[Wed Jan 29 12:48:30.080491 2020] [wsgi:error] [pid 1824:tid 1116] [client 172.16.19.174:45466] found user\r, referer: http://172.16.2.61/login
[Wed Jan 29 12:52:24.704601 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.18.232:48412] 2020-09-01 00:00:00\r, referer: http://172.16.2.61/documents
[Wed Jan 29 12:52:24.912153 2020] [wsgi:error] [pid 1824:tid 1108] [client 172.16.18.232:48412] 2020-09-01 00:00:00\r, referer: http://172.16.2.61/
[Thu Feb 20 11:50:11.494465 2020] [wsgi:error] [pid 6368:tid 964] [client ::1:49912] found user\r, referer: http://localhost/login
[Thu Feb 20 11:55:59.749558 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099] mod_wsgi (pid=6480): Failed to exec Python script file 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'.
[Thu Feb 20 11:55:59.750561 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099] mod_wsgi (pid=6480): Exception occurred processing WSGI script 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'.
[Thu Feb 20 11:55:59.763596 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099] Traceback (most recent call last):\r
[Thu Feb 20 11:55:59.763596 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi", line 5, in <module>\r
[Thu Feb 20 11:55:59.763596 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099]     from app import app as application\r
[Thu Feb 20 11:55:59.763596 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 20, in <module>\r
[Thu Feb 20 11:55:59.763596 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099]     app.config.from_envvar('APPLICATION_SETTINGS')\r
[Thu Feb 20 11:55:59.763596 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\config.py", line 105, in from_envvar\r
[Thu Feb 20 11:55:59.763596 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099]     raise RuntimeError(\r
[Thu Feb 20 11:55:59.763596 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50099] RuntimeError: The environment variable 'APPLICATION_SETTINGS' is not set and as such configuration could not be loaded.  Set this variable and make it point to a configuration file\r
[Thu Feb 20 11:56:06.508743 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098] mod_wsgi (pid=6480): Failed to exec Python script file 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'.
[Thu Feb 20 11:56:06.508743 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098] mod_wsgi (pid=6480): Exception occurred processing WSGI script 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'.
[Thu Feb 20 11:56:06.508743 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098] Traceback (most recent call last):\r
[Thu Feb 20 11:56:06.508743 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi", line 5, in <module>\r
[Thu Feb 20 11:56:06.508743 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098]     from app import app as application\r
[Thu Feb 20 11:56:06.508743 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 20, in <module>\r
[Thu Feb 20 11:56:06.508743 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098]     app.config.from_envvar('APPLICATION_SETTINGS')\r
[Thu Feb 20 11:56:06.508743 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\config.py", line 105, in from_envvar\r
[Thu Feb 20 11:56:06.509746 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098]     raise RuntimeError(\r
[Thu Feb 20 11:56:06.509746 2020] [wsgi:error] [pid 6480:tid 952] [client ::1:50098] RuntimeError: The environment variable 'APPLICATION_SETTINGS' is not set and as such configuration could not be loaded.  Set this variable and make it point to a configuration file\r
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125] mod_wsgi (pid=6480): Failed to exec Python script file 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'.
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125] mod_wsgi (pid=6480): Exception occurred processing WSGI script 'C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi'.
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125] Traceback (most recent call last):\r
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee/index/web.wsgi", line 5, in <module>\r
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125]     from app import app as application\r
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125]   File "C:/Users/admin/Desktop/server_deploy/mentor_mentee\\app.py", line 20, in <module>\r
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125]     app.config.from_envvar('APPLICATION_SETTINGS')\r
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125]   File "c:\\users\\admin\\desktop\\server_deploy\\mentor_mentee\\venv\\lib\\site-packages\\flask\\config.py", line 105, in from_envvar\r
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125]     raise RuntimeError(\r
[Thu Feb 20 11:57:07.652753 2020] [wsgi:error] [pid 6480:tid 948] [client ::1:50125] RuntimeError: The environment variable 'APPLICATION_SETTINGS' is not set and as such configuration could not be loaded.  Set this variable and make it point to a configuration file\r
